#!/usr/bin/python
# -*- coding: UTF-8 -*-

ctable = [
        ("a", "あ"),
        ("u", "う"),
        ("i", "い"),
        ("e", "え"),
        ("o", "お"),
        ("ka", "か"),
        ("ki", "き"),
        ("ku", "く"),
        ("ke", "け"),
        ("ko", "こ"),
        ("kya", "きゃ"),
        ("kyu", "きゅ"),
        ("kyo", "きょ"),
        ("sa", "さ"),
        ("si", "し"),
        ("shi", "し"),
        ("su", "す"),
        ("se", "せ"),
        ("so", "そ"),
        ("sya", "しゃ"),
        ("syu", "しゅ"),
        ("syo", "しょ"),
        ("sha", "しゃ"),
        ("shu", "しゅ"),
        ("sho", "しょ"),
        ("ta", "た"),
        ("ti", "ち"),
        ("ti", "てぃ"),
        ("chi", "ち"),
        ("tu", "つ"),
        ("tsu", "つ"),
        ("te", "て"),
        ("to", "と"),
        ("tya", "ちゃ"),
        ("tyu", "ちゅ"),
        ("tyo", "ちょ"),
        ("cha", "ちゃ"),
        ("chu", "ちゅ"),
        ("cho", "ちょ"),
        ("na", "な"),
        ("ni", "に"),
        ("nu", "ぬ"),
        ("ne", "ね"),
        ("no", "の"),
        ("nya", "にゃ"),
        ("nyu", "にゅ"),
        ("nyo", "にょ"),
        ("ha", "は"),
        ("hi", "ひ"),
        ("hu", "ふ"),
        ("fu", "ふ"),
        ("fi", "ふぃ"),
        ("fo", "ふぉ"),
        ("he", "へ"),
        ("ho", "ほ"),
        ("hya", "ひゃ"),
        ("hyu", "ひゅ"),
        ("hyo", "ひょ"),
        ("ma", "ま"),
        ("mi", "み"),
        ("mu", "む"),
        ("me", "め"),
        ("mo", "も"),
        ("mya", "みゃ"),
        ("myu", "みゅ"),
        ("myo", "みょ"),
        ("ya", "や"),
        ("yu", "ゆ"),
        ("yo", "よ"),
        ("ra", "ら"),
        ("ri", "り"),
        ("ru", "る"),
        ("re", "れ"),
        ("ro", "ろ"),
        ("rya", "りゃ"),
        ("ryu", "りゅ"),
        ("ryo", "りょ"),
        ("wa", "わ"),
        ("wo", "を"),
        ("o", "を"),
        ("ga", "が"),
        ("gi", "ぎ"),
        ("gu", "ぐ"),
        ("ge", "げ"),
        ("go", "ご"),
        ("gya", "ぎゃ"),
        ("gyu", "ぎゅ"),
        ("gyo", "ぎょ"),
        ("za", "ざ"),
        ("zi", "じ"),
        ("ji", "じ"),
        ("zu", "ず"),
        ("ze", "ぜ"),
        ("zo", "ぞ"),
        ("zya", "じゃ"),
        ("zyu", "じゅ"),
        ("zyo", "じょ"),
        ("ja", "じゃ"),
        ("jya", "じゃ"),
        ("ju", "じゅ"),
        ("jyu", "じゅ"),
        ("jo", "じょ"),
        ("jyo", "じょ"),
        ("da", "だ"),
        ("di", "ぢ"),
        ("ji", "ぢ"),
        ("du", "づ"),
        ("zu", "づ"),
        ("de", "で"),
        ("do", "ど"),
        ("dya", "ぢゃ"),
        ("dyu", "ぢゅ"),
        ("dyo", "ぢょ"),
        ("ja", "ぢゃ"),
        ("jya", "ぢゃ"),
        ("ju", "ぢゅ"),
        ("jyu", "ぢゅ"),
        ("jo", "ぢょ"),
        ("jyo", "ぢょ"),
        ("ba", "ば"),
        ("bu", "ぶ"),
        ("bi", "び"),
        ("be", "べ"),
        ("bo", "ぼ"),
        ("bya", "びゃ"),
        ("byu", "びゅ"),
        ("byo", "びょ"),
        ("pa", "ぱ"),
        ("pu", "ぷ"),
        ("pi", "ぴ"),
        ("pe", "ぺ"),
        ("po", "ぽ"),
        ("pya", "ぴゃ"),
        ("pyu", "ぴゅ"),
        ("pyo", "ぴょ"),
        ("n'", "ん"),
        ("n", "ん"),

        ("a", "ア"),
        ("u", "ウ"),
        ("i", "イ"),
        ("e", "エ"),
        ("o", "オ"),
        ("ka", "カ"),
        ("ki", "キ"),
        ("ku", "ク"),
        ("ke", "ケ"),
        ("ko", "コ"),
        ("kya", "キャ"),
        ("kyu", "キュ"),
        ("kyo", "キョ"),
        ("kye", "キェ"),
        ("sa", "サ"),
        ("si", "シ"),
        ("shi", "シ"),
        ("su", "ス"),
        ("se", "セ"),
        ("so", "ソ"),
        ("sya", "シャ"),
        ("syu", "シュ"),
        ("syo", "ショ"),
        ("sye", "シェ"),
        ("sha", "シャ"),
        ("shu", "シュ"),
        ("sho", "ショ"),
        ("she", "シェ"),
        ("ta", "タ"),
        ("ti", "チ"),
        ("ti", "ティ"),
        ("chi", "チ"),
        ("tu", "ツ"),
        ("tsu", "ツ"),
        ("te", "テ"),
        ("to", "ト"),
        ("tya", "チャ"),
        ("tyu", "チュ"),
        ("tyo", "チョ"),
        ("tye", "チェ"),
        ("cha", "チャ"),
        ("chu", "チュ"),
        ("cho", "チョ"),
        ("che", "チェ"),
        ("na", "ナ"),
        ("ni", "ニ"),
        ("nu", "ヌ"),
        ("ne", "ネ"),
        ("no", "ノ"),
        ("nya", "ニャ"),
        ("nyu", "ニュ"),
        ("nyo", "ニョ"),
        ("nye", "ニェ"),
        ("ha", "ハ"),
        ("hi", "ヒ"),
        ("hu", "フ"),
        ("fu", "フ"),
        ("fi", "フィ"),
        ("fo", "フォ"),
        ("he", "ヘ"),
        ("ho", "ホ"),
        ("hya", "ヒャ"),
        ("hyu", "ヒュ"),
        ("hyo", "ヒョ"),
        ("hye", "ヒェ"),
        ("ma", "マ"),
        ("mi", "ミ"),
        ("mu", "ム"),
        ("me", "メ"),
        ("mo", "モ"),
        ("mya", "ミャ"),
        ("myu", "ミュ"),
        ("myo", "ミョ"),
        ("mye", "ミェ"),
        ("ya", "ヤ"),
        ("yu", "ユ"),
        ("yo", "ヨ"),
        ("ra", "ラ"),
        ("ri", "リ"),
        ("ru", "ル"),
        ("re", "レ"),
        ("ro", "ロ"),
        ("rya", "リャ"),
        ("ryu", "リュ"),
        ("ryo", "リョ"),
        ("rye", "リェ"),
        ("wa", "ワ"),
        ("ga", "ガ"),
        ("gi", "ギ"),
        ("gu", "グ"),
        ("ge", "ゲ"),
        ("go", "ゴ"),
        ("gya", "ギャ"),
        ("gyu", "ギュ"),
        ("gyo", "ギョ"),
        ("gye", "ギェ"),
        ("za", "ザ"),
        ("zi", "ジ"),
        ("ji", "ジ"),
        ("zu", "ズ"),
        ("ze", "ゼ"),
        ("zo", "ゾ"),
        ("zya", "ジャ"),
        ("zyu", "ジュ"),
        ("zyo", "ジョ"),
        ("zye", "ジェ"),
        ("ja", "ジャ"),
        ("jya", "ジャ"),
        ("ju", "ジュ"),
        ("jyu", "ジュ"),
        ("jo", "ジョ"),
        ("jyo", "ジョ"),
        ("je", "ジェ"),
        ("jye", "ジェ"),
        ("da", "ダ"),
        ("di", "ヂ"),
        ("ji", "ヂ"),
        ("du", "ヅ"),
        ("zu", "ヅ"),
        ("de", "デ"),
        ("do", "ド"),
        ("dya", "ヂャ"),
        ("dyu", "ヂュ"),
        ("dyo", "ヂョ"),
        ("dye", "ヂェ"),
        ("ja", "ヂャ"),
        ("jya", "ヂャ"),
        ("ju", "ヂュ"),
        ("jyu", "ヂュ"),
        ("jo", "ヂョ"),
        ("jyo", "ヂョ"),
        ("je", "ヂェ"),
        ("jye", "ヂェ"),
        ("ba", "バ"),
        ("bu", "ブ"),
        ("bi", "ビ"),
        ("be", "ベ"),
        ("bo", "ボ"),
        ("bya", "ビャ"),
        ("byu", "ビュ"),
        ("byo", "ビョ"),
        ("bye", "ビェ"),
        ("pa", "パ"),
        ("pu", "プ"),
        ("pi", "ピ"),
        ("pe", "ペ"),
        ("po", "ポ"),
        ("pya", "ピャ"),
        ("pyu", "ピュ"),
        ("pyo", "ピョ"),
        ("pye", "ピェ"),
        ("n'", "ン"),
        ("n", "ン"),
]
# Most of them aren't very meaningful
ctable2 = [
        ("kk", "k"),
        ("ss", "s"),
        ("tt", "t"),
        ("tch", "ch"),
        ("cch", "ch"),
        ("hh", "h"),
        ("mm", "m"),
        ("rr", "r"),
        ("gg", "g"),
        ("zz", "z"),
        ("dd", "d"),
        ("dj", "j"),
        ("jj", "j"),
        ("bb", "b"),
        ("pp", "p"),
]


###########################################################
# Match romaji with kana                                  #
###########################################################
def romaji_kana_match(r, h):
    small_tsus = ["っ", "ッ"]
    prolongation_mark = "ー"
    lm = "" # Last matched romaji vowel
    while True:
        # Both are empty
        if r == "" and h == "":
            return True
        # Only one is empty
        if r == "" or h == "":
            return False
        prefix_found = False
        for (rp, hp) in ctable:
            # Does Python have deep breaks ?

            if r[0:len(rp)] == rp and h[0:len(hp)] == hp:
                lm = r[len(rp)-1]
                r = r[len(rp):len(r)]
                h = h[len(hp):len(h)]
                prefix_found = True # Level 2 continue
                break
        if prefix_found:
            continue
        # Well, it is False here, but anyway :-)
        prefix_found = False
        for small_tsu in small_tsus:
            if h[0:len(small_tsu)] == small_tsu:
                for (rp, rr) in ctable2:
                    if r[0:len(rp)] == rp:
                        lm = ""
                        r = rr + r[len(rp):len(r)]
                        h = h[len(small_tsu):len(h)]
                        prefix_found = True
                        break # Level 3 continue, need to fix it
                if prefix_found:
                    break
        if prefix_found:
            continue
        if h[0:len(prolongation_mark)] == prolongation_mark:
            # Just a sanity check
            if lm == r[0] and lm in ["a", "e", "i", "o", "u"]:
                # Keep lm, if there are more ーs ;-)
                lm = lm
                r = r[1:len(r)]
                h = h[len(prolongation_mark):len(h)]
                continue
        return False
