#!/usr/bin/python
# -*- coding: UTF-8 -*-

import warnings

ctable = [
        (U"a",U"あ"),
        (U"u",U"う"),
        (U"i",U"い"),
        (U"e",U"え"),
        (U"o",U"お"),
        (U"ka",U"か"),
        (U"ki",U"き"),
        (U"ku",U"く"),
        (U"ke",U"け"),
        (U"ko",U"こ"),
        (U"kya",U"きゃ"),
        (U"kyu",U"きゅ"),
        (U"kyo",U"きょ"),
        (U"sa",U"さ"),
        (U"si",U"し"),
        (U"shi",U"し"),
        (U"su",U"す"),
        (U"se",U"せ"),
        (U"so",U"そ"),
        (U"sya",U"しゃ"),
        (U"syu",U"しゅ"),
        (U"syo",U"しょ"),
        (U"sha",U"しゃ"),
        (U"shu",U"しゅ"),
        (U"sho",U"しょ"),
        (U"ta",U"た"),
        (U"ti",U"ち"),
        (U"ti",U"てぃ"),
        (U"chi",U"ち"),
        (U"tu",U"つ"),
        (U"tsu",U"つ"),
        (U"te",U"て"),
        (U"to",U"と"),
        (U"tya",U"ちゃ"),
        (U"tyu",U"ちゅ"),
        (U"tyo",U"ちょ"),
        (U"cha",U"ちゃ"),
        (U"chu",U"ちゅ"),
        (U"cho",U"ちょ"),
        (U"na",U"な"),
        (U"ni",U"に"),
        (U"nu",U"ぬ"),
        (U"ne",U"ね"),
        (U"no",U"の"),
        (U"nya",U"にゃ"),
        (U"nyu",U"にゅ"),
        (U"nyo",U"にょ"),
        (U"ha",U"は"),
        (U"hi",U"ひ"),
        (U"hu",U"ふ"),
        (U"fu",U"ふ"),
        (U"fi",U"ふぃ"),
        (U"fo",U"ふぉ"),
        (U"he",U"へ"),
        (U"ho",U"ほ"),
        (U"hya",U"ひゃ"),
        (U"hyu",U"ひゅ"),
        (U"hyo",U"ひょ"),
        (U"ma",U"ま"),
        (U"mi",U"み"),
        (U"mu",U"む"),
        (U"me",U"め"),
        (U"mo",U"も"),
        (U"mya",U"みゃ"),
        (U"myu",U"みゅ"),
        (U"myo",U"みょ"),
        (U"ya",U"や"),
        (U"yu",U"ゆ"),
        (U"yo",U"よ"),
        (U"ra",U"ら"),
        (U"ri",U"り"),
        (U"ru",U"る"),
        (U"re",U"れ"),
        (U"ro",U"ろ"),
        (U"rya",U"りゃ"),
        (U"ryu",U"りゅ"),
        (U"ryo",U"りょ"),
        (U"wa",U"わ"),
        (U"wo",U"を"),
        (U"o",U"を"),
        (U"ga",U"が"),
        (U"gi",U"ぎ"),
        (U"gu",U"ぐ"),
        (U"ge",U"げ"),
        (U"go",U"ご"),
        (U"gya",U"ぎゃ"),
        (U"gyu",U"ぎゅ"),
        (U"gyo",U"ぎょ"),
        (U"za",U"ざ"),
        (U"zi",U"じ"),
        (U"ji",U"じ"),
        (U"zu",U"ず"),
        (U"ze",U"ぜ"),
        (U"zo",U"ぞ"),
        (U"zya",U"じゃ"),
        (U"zyu",U"じゅ"),
        (U"zyo",U"じょ"),
        (U"ja",U"じゃ"),
        (U"jya",U"じゃ"),
        (U"ju",U"じゅ"),
        (U"jyu",U"じゅ"),
        (U"jo",U"じょ"),
        (U"jyo",U"じょ"),
        (U"da",U"だ"),
        (U"di",U"ぢ"),
        (U"ji",U"ぢ"),
        (U"du",U"づ"),
        (U"zu",U"づ"),
        (U"de",U"で"),
        (U"do",U"ど"),
        (U"dya",U"ぢゃ"),
        (U"dyu",U"ぢゅ"),
        (U"dyo",U"ぢょ"),
        (U"ja",U"ぢゃ"),
        (U"jya",U"ぢゃ"),
        (U"ju",U"ぢゅ"),
        (U"jyu",U"ぢゅ"),
        (U"jo",U"ぢょ"),
        (U"jyo",U"ぢょ"),
        (U"ba",U"ば"),
        (U"bu",U"ぶ"),
        (U"bi",U"び"),
        (U"be",U"べ"),
        (U"bo",U"ぼ"),
        (U"bya",U"びゃ"),
        (U"byu",U"びゅ"),
        (U"byo",U"びょ"),
        (U"pa",U"ぱ"),
        (U"pu",U"ぷ"),
        (U"pi",U"ぴ"),
        (U"pe",U"ぺ"),
        (U"po",U"ぽ"),
        (U"pya",U"ぴゃ"),
        (U"pyu",U"ぴゅ"),
        (U"pyo",U"ぴょ"),
        (U"n'",U"ん"),
        (U"n",U"ん"),

        (U"a",U"ア"),
        (U"u",U"ウ"),
        (U"i",U"イ"),
        (U"e",U"エ"),
        (U"o",U"オ"),
        (U"ka",U"カ"),
        (U"ki",U"キ"),
        (U"ku",U"ク"),
        (U"ke",U"ケ"),
        (U"ko",U"コ"),
        (U"kya",U"キャ"),
        (U"kyu",U"キュ"),
        (U"kyo",U"キョ"),
        (U"kye",U"キェ"),
        (U"sa",U"サ"),
        (U"si",U"シ"),
        (U"shi",U"シ"),
        (U"su",U"ス"),
        (U"se",U"セ"),
        (U"so",U"ソ"),
        (U"sya",U"シャ"),
        (U"syu",U"シュ"),
        (U"syo",U"ショ"),
        (U"sye",U"シェ"),
        (U"sha",U"シャ"),
        (U"shu",U"シュ"),
        (U"sho",U"ショ"),
        (U"she",U"シェ"),
        (U"ta",U"タ"),
        (U"ti",U"チ"),
        (U"ti",U"ティ"),
        (U"chi",U"チ"),
        (U"tu",U"ツ"),
        (U"tsu",U"ツ"),
        (U"te",U"テ"),
        (U"to",U"ト"),
        (U"tya",U"チャ"),
        (U"tyu",U"チュ"),
        (U"tyo",U"チョ"),
        (U"tye",U"チェ"),
        (U"cha",U"チャ"),
        (U"chu",U"チュ"),
        (U"cho",U"チョ"),
        (U"che",U"チェ"),
        (U"na",U"ナ"),
        (U"ni",U"ニ"),
        (U"nu",U"ヌ"),
        (U"ne",U"ネ"),
        (U"no",U"ノ"),
        (U"nya",U"ニャ"),
        (U"nyu",U"ニュ"),
        (U"nyo",U"ニョ"),
        (U"nye",U"ニェ"),
        (U"ha",U"ハ"),
        (U"hi",U"ヒ"),
        (U"hu",U"フ"),
        (U"fu",U"フ"),
        (U"fi",U"フィ"),
        (U"fo",U"フォ"),
        (U"he",U"ヘ"),
        (U"ho",U"ホ"),
        (U"hya",U"ヒャ"),
        (U"hyu",U"ヒュ"),
        (U"hyo",U"ヒョ"),
        (U"hye",U"ヒェ"),
        (U"ma",U"マ"),
        (U"mi",U"ミ"),
        (U"mu",U"ム"),
        (U"me",U"メ"),
        (U"mo",U"モ"),
        (U"mya",U"ミャ"),
        (U"myu",U"ミュ"),
        (U"myo",U"ミョ"),
        (U"mye",U"ミェ"),
        (U"ya",U"ヤ"),
        (U"yu",U"ユ"),
        (U"yo",U"ヨ"),
        (U"ra",U"ラ"),
        (U"ri",U"リ"),
        (U"ru",U"ル"),
        (U"re",U"レ"),
        (U"ro",U"ロ"),
        (U"rya",U"リャ"),
        (U"ryu",U"リュ"),
        (U"ryo",U"リョ"),
        (U"rye",U"リェ"),
        (U"wa",U"ワ"),
        (U"ga",U"ガ"),
        (U"gi",U"ギ"),
        (U"gu",U"グ"),
        (U"ge",U"ゲ"),
        (U"go",U"ゴ"),
        (U"gya",U"ギャ"),
        (U"gyu",U"ギュ"),
        (U"gyo",U"ギョ"),
        (U"gye",U"ギェ"),
        (U"za",U"ザ"),
        (U"zi",U"ジ"),
        (U"ji",U"ジ"),
        (U"zu",U"ズ"),
        (U"ze",U"ゼ"),
        (U"zo",U"ゾ"),
        (U"zya",U"ジャ"),
        (U"zyu",U"ジュ"),
        (U"zyo",U"ジョ"),
        (U"zye",U"ジェ"),
        (U"ja",U"ジャ"),
        (U"jya",U"ジャ"),
        (U"ju",U"ジュ"),
        (U"jyu",U"ジュ"),
        (U"jo",U"ジョ"),
        (U"jyo",U"ジョ"),
        (U"je",U"ジェ"),
        (U"jye",U"ジェ"),
        (U"da",U"ダ"),
        (U"di",U"ヂ"),
        (U"ji",U"ヂ"),
        (U"du",U"ヅ"),
        (U"zu",U"ヅ"),
        (U"de",U"デ"),
        (U"do",U"ド"),
        (U"dya",U"ヂャ"),
        (U"dyu",U"ヂュ"),
        (U"dyo",U"ヂョ"),
        (U"dye",U"ヂェ"),
        (U"ja",U"ヂャ"),
        (U"jya",U"ヂャ"),
        (U"ju",U"ヂュ"),
        (U"jyu",U"ヂュ"),
        (U"jo",U"ヂョ"),
        (U"jyo",U"ヂョ"),
        (U"je",U"ヂェ"),
        (U"jye",U"ヂェ"),
        (U"ba",U"バ"),
        (U"bu",U"ブ"),
        (U"bi",U"ビ"),
        (U"be",U"ベ"),
        (U"bo",U"ボ"),
        (U"bya",U"ビャ"),
        (U"byu",U"ビュ"),
        (U"byo",U"ビョ"),
        (U"bye",U"ビェ"),
        (U"pa",U"パ"),
        (U"pu",U"プ"),
        (U"pi",U"ピ"),
        (U"pe",U"ペ"),
        (U"po",U"ポ"),
        (U"pya",U"ピャ"),
        (U"pyu",U"ピュ"),
        (U"pyo",U"ピョ"),
        (U"pye",U"ピェ"),
        (U"n'",U"ン"),
        (U"n",U"ン"),
]
# Most of them aren't very meaningful
ctable2 = [
        (U"kk",U"k"),
        (U"ss",U"s"),
        (U"tt",U"t"),
        (U"tch",U"ch"),
        (U"cch",U"ch"),
        (U"hh",U"h"),
        (U"mm",U"m"),
        (U"rr",U"r"),
        (U"gg",U"g"),
        (U"zz",U"z"),
        (U"dd",U"d"),
        (U"dj",U"j"),
        (U"jj",U"j"),
        (U"bb",U"b"),
        (U"pp",U"p"),
]

###########################################################
# Match romaji with kana                                  #
###########################################################
def romaji_kana_match(r, h):
    small_tsus = [U"っ", U"ッ"]
    prolongation_mark = U"ー"
    lm = U"" # Last matched romaji vowel
    while True:
        # Both are empty
        if r == U"" and h == U"":
            return True
        # Only one is empty
        if r == U"" or h == U"":
            return False
        prefix_found = False
        for (rp, hp) in ctable:
            # Does Python have deep breaks ?

            if r[0:len(rp)] == rp and h[0:len(hp)] == hp:
                lm = r[len(rp)-1]
                r = r[len(rp):len(r)]
                h = h[len(hp):len(h)]
                prefix_found = True # Level 2 continue
                break
        if prefix_found:
            continue
        # Well, it is False here, but anyway :-)
        prefix_found = False
        for small_tsu in small_tsus:
            if h[0:len(small_tsu)] == small_tsu:
                for (rp, rr) in ctable2:
                    if r[0:len(rp)] == rp:
                        lm = U""
                        r = rr + r[len(rp):len(r)]
                        h = h[len(small_tsu):len(h)]
                        prefix_found = True
                        break # Level 3 continue, need to fix it
                if prefix_found:
                    break
        if prefix_found:
            continue
        if h[0:len(prolongation_mark)] == prolongation_mark:
        # Just a sanity check
            if lm == r[0] and lm in [U"a", U"e", U"i", U"o", U"u"]:
                # Keep lm, if there are more ーs ;-)
                lm = lm
                r = r[1:len(r)]
                h = h[len(prolongation_mark):len(h)]
                continue
        return False
